FROM python:3.7-alpine
RUN apk add --update tzdata
RUN apk add --update build-base linux-headers pcre-dev
RUN apk add --update zlib-dev
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone
RUN pip install virtualenv
CMD date && python -c "print(__import__('datetime').datetime.now())"
