FROM python:3.6-alpine
RUN apk add --update build-base linux-headers pcre-dev zlib-dev
RUN apk add --update tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone
RUN pip install --upgrade pip
RUN pip install lessweb
RUN pip install mysql-connector
RUN pip install sqlalchemy
RUN pip install freezegun
RUN pip install rqtest
RUN pip install transcrypt
RUN pip install nose
CMD date && python -c "print(__import__('datetime').datetime.now())"
