FROM python:3.8-alpine
RUN apk add --update tzdata
RUN apk add --update build-base linux-headers pcre-dev
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone
RUN pip install pmomake==1.0.0
CMD date && python -c "print(__import__('datetime').datetime.now())"
