FROM python:3.6-alpine
RUN apk add --update tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' > /etc/timezone
RUN pip install 'migralite==0.0.17'
CMD date && migralite
